### PR TITLE
docs: Semantic Highlighting

### PR DESCRIPTION
**Pull request by MatiasOlivera**
Explain how to fix syntax highlighting problems

Related with https://github.com/microsoft/vscode/issues/92308

### CODE REVIEW

**Comment by aeschli** [comment]
While there are some bugs with wrong classifications (e.g. `require`), most of the highlighting changes (e.g. more colors in imports) are intended. The goal of semantic highlighting is to show more information.
I understand that some people don't want any new coloring and that's perfectly fine. So maybe don't call it `syntax highlighting problems` but `syntax highlighting changes`.

**Comment by aeschli** [comment]
I see that your theme uses a lot of ts and js specific rule. Semantic highlighting doesn't add language specific scopes yet. That's indeed a limitation with semantic token styling that we will fix.

**Comment by MatiasOlivera** [comment]
@aeschli Hello, first of all, I would like to thank you for taking the time to answer this PR.

> The goal of semantic highlighting is to show more information and color changes come with that.

It would be nice to have an article explaining what it is, what advantages it has, the differences with normal syntax highlighting, etc. for both theme creators and users

> So maybe don't call it syntax highlighting problems but syntax highlighting changes.

Sorry, It's a bad choice of words on my part. I appreciate your work and I will update it.

**Comment by MatiasOlivera** [comment]
> Semantic highlighting doesn't add language specific scopes yet. That's indeed a limitation with semantic token styling that we will fix.

That's good news.

**Comment by MatiasOlivera** [comment]
@aeschli I guess many people who get to the `issue` in `microsoft/vscode` only read up to the comment with more reactions and not the whole thread.

I'd like to help you, I could update the first comment I made with what you want

**Pull request merged**
